# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrule = opacity 0.89 override 0.89 override, match:class .*
windowrule = match:class .*, no_blur off
windowrule = match:class ^()$, match:title ^()$, no_blur on

windowrule = no_blur on, match:class gimp
windowrule = opacity 1 override 1 override, match:class gimp

# tearing
windowrule = immediate on, match:title Minecraft.*
windowrule = match:title Minecraft.*, float on

workspace = 1, monitor:DP-3
workspace = 2, monitor:DP-3
workspace = 3, monitor:DP-3
workspace = 4, monitor:DP-3
workspace = 5, monitor:DP-3
workspace = 6, monitor:DP-3
workspace = 7, monitor:DP-3
workspace = 8, monitor:DP-3
workspace = 9, monitor:DP-3
workspace = 10, monitor:DP-3
